version: '2.0'

services:
  api:
    # network_mode: "host"
    build: ./api
    ports:
      - "5000:5000"
  mongo:
    image: "mongo:4.1.1-xenial"
    logging:
      driver: "none"
    ports:
      - "27017:27017"
  api_tests:
    build: ./api_tests
