version: '2.0'

services:
  api:
    build: ./api_falcon
    ports:
      - "5000:5000"
    expose:
      - 5000
    environment:
      - "PYTHONUNBUFFERED=1"
    depends_on:
      - mongo
  
  mongo:
    image: mongo:latest
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
    expose:
        - 27017
    command: mongod --smallfiles --logpath=/dev/null

  api_tests:
    build: ./api_tests
    environment:
      - "PYTHONUNBUFFERED=1"
    entrypoint: /bin/bash -c "cd / && python /frontend_tests.py"

  frontend:
    build: ./frontend_example
    ports:
      - "80:80"

  portainer:
    image: portainer/portainer
    command: -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./portainer_data:/data
    ports:
      - "9000:9000"
