version: '2.0'

services:
  api:
    build: ./api
    ports:
      - "127.0.0.1:5000:5000"
  mongo:
    image: "mongo:4.1.1-xenial"
    logging:
      driver: "none"
    expose:
      - "27017"
  api_tests:
    build: ./api_tests
